name: tesou
description: An app to share position with trusted people.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  aosp_location:
    path: aosp_location
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  flutter_foreground_task: 9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: 8.2.1
  # TEMPORARY
  flutter_map_geojson:
    git: https://github.com/NomiAdam/flutter_map_geojson
  intl: 0.20.2
  html: 0.15.6
  http: ^1.5.0-beta.2
  latlong2: 0.9.1
  path_provider: 2.1.5
  permission_handler: 12.0.1
  shared_preferences: 2.5.3
  url_launcher: 6.3.2
  web_socket_channel: 3.0.3
  geoxml: 2.6.2
  file_picker: 10.2.0
  web: 1.1.1
  # TEMPORARY
  flutter_beep:
    git:
      url: https://github.com/trietho/flutter_beep.git

dev_dependencies:
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#4caf50"

### For generating notification icon with `flutter pub run flutter_launcher_icons:main`.
# flutter_icons:
#   android: "ic_notification"
#   ios: true
#   image_path: "assets/icon/icon_foreground_big.png"
#   remove_alpha_ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - "assets/icon/icon_foreground_big.png"
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
